name: Publish ScanCode Docker image to ghcr.io

 # This is executed automatically on a tag
 #
 # Summary of the steps:
 # - Build a Docker image of scancode-toolkit based on the Dockerfile
 # - Publish the new Docker image to ghcr.io/elrayle/scancode-toolkit

on:
    workflow_dispatch:
    push:
      tags:
        - "v*.*.*"

permissions: {}

env:
  TAG: $(date +%s)

jobs:

  setup-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Set tag
        id: set-tag
        run: |
          if [ ${{ github.ref_type }} != 'tag' ]; then
            echo "tag=${{ github.sha }}" >> "$GITHUB_OUTPUT"
          else
            full_ref=${{ github.ref }}
            echo "tag=${full_ref#refs/tags/}" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

  build_scancode_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: setup-tag
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        env:
          TAG: ${{ needs.setup-tag.outputs.tag }}
        run: |
          echo "*****   logging in to Docker for ghcr.io"
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          echo "*****   building Docker image"
          echo "*****   cmd: docker build . --tag ghcr.io/${{ github.repository }}:${{ env.TAG }}"
          docker build . --tag ghcr.io/${{ github.repository }}:${{ env.TAG }}
          echo "*****   pushing Docker image to ghcr.io"
          echo "*****   cmd: docker push ghcr.io/${{ github.repository }}:${{ env.TAG }}"
          docker push ghcr.io/${{ github.repository }}:${{ env.TAG }}





# jobs:
#     set-tags:
#       runs-on: ubuntu-20.04
#       outputs:
#         tags: ${{ steps.set-tags.outputs.tags }}
#         main-tag: ${{ steps.set-tags.outputs.main-tag }}
#       steps:
#         - uses: actions/checkout@v2
#         - name: Set tags
#           id: set-tags
#           run: |
#             if [ ${{ github.ref_type }} = 'tag' ]; then
#               full_ref=${{ github.ref }}
#               vtag=${full_ref#refs/tags/}
#               echo "tags=${{ github.repository }}:${vtag},${{ github.repository }}:latest" >> "$GITHUB_OUTPUT"
#               echo "main-tag=${{ github.repository }}:${vtag}" >> "$GITHUB_OUTPUT"
#             else
#               echo "tags=${{ github.repository }}:${{ github.sha }}" >> "$GITHUB_OUTPUT"
#               echo "main-tag=${{ github.repository }}:${{ github.sha }}" >> "$GITHUB_OUTPUT"
#             fi
#           shell: bash

#     build_scancode_for_ghcr:
#       name: Build ScanCode Docker image
#       runs-on: ubuntu-20.04
#       permissions:
#         contents: read
#         packages: write
#       needs: set-tags
#       steps:
#         - uses: actions/checkout@v2
  
#         - name: Build and publish Docker image to ghcr.io/elrayle/scancode-toolkit
#           uses: macbre/push-to-ghcr@master
#           env:
#             MAIN_TAG: ${{ needs.set-tags.outputs.main-tag }}
#           with:
#             image_name: ${{ github.repository }}
#             image_tag: ${{ env.MAIN_TAG }}
#             github_token: ${{ secrets.GH_TOKEN }}
