name: Build ScanCode Docker image

 # This is executed automatically on a tag
 #
 # Summary of the steps:
 # - Build a Docker image of scancode-toolkit based on the Dockerfile
 # - Run scancode-toolkit on the Docker image to generate scan results
 # - Build a new Docker image including the previously generated images plus scan results
 # - Publish the new Docker image to ghcr.io/nexB/scancode-toolkit
 # - Smoke test the new Docker image

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

permissions: {}

env:
  TAG: $(date +%s)

jobs:

  setup-tag:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.set-tag.outputs.tag }}
    steps:
      - uses: actions/checkout@v2
      - name: Set tag
        id: set-tag
        run: |
          if [ ${{ github.ref_type }} != 'tag' ]; then
            echo "tag=${{ github.sha }}" >> "$GITHUB_OUTPUT"
          else
            full_ref=${{ github.ref }}
            echo "tag=${full_ref#refs/tags/}" >> "$GITHUB_OUTPUT"
          fi
        shell: bash

  build_scancode_docker_image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    needs: setup-tag
    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        env:
          TAG: ${{ needs.setup-tag.outputs.tag }}
        run: |
          echo "*****   logging in to Docker for ghcr.io"
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

          echo "*****   building Docker image"
          echo "*****   cmd: docker build . --tag ghcr.io/${{ github.repository }}:${{ env.TAG }}"
          docker build . --tag ghcr.io/${{ github.repository }}:${{ env.TAG }}

          echo "*****   pushing Docker image to ghcr.io"
          echo "*****   cmd: docker push ghcr.io/${{ github.repository }}:${{ env.TAG }}"
          docker push ghcr.io/${{ github.repository }}:${{ env.TAG }}

      # - name: Scan Docker image
      #   run: docker run --rm scancode-only-image:$(date +%s) --version

      # - name: Build new Docker image with scan results
      #   run: docker build . --file Dockerfile --tag ghcr.io/elrayle/scancode-toolkit:$(date +%s)

      # - name: Publish Docker image to ghcr.io/nexB/scancode-toolkit
      #   uses: macbre/push-to-ghcr@master
      #   with:
      #     image_name: ${{ github.repository }}
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

  # smoke_test_docker_image:
  #   name: Smoke test ScanCode Docker image
  #   runs-on: ubuntu-20.04

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Run ScanCode Docker image
  #       run: docker run --rm scancode-only-image:$(date +%s) --version
